# Generated by Django 3.1.7 on 2021-03-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userfavouritelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPresetLocation',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.location')),
            ],
            options={
                'verbose_name': 'Add Preset Location',
                'verbose_name_plural': 'Add Preset Loaction',
            },
            bases=('app.location',),
        ),
        migrations.AlterModelOptions(
            name='userfavouritelist',
            options={'verbose_name': 'User Favourite List', 'verbose_name_plural': 'User Favourite List'},
        ),
    ]
