# Generated by Django 3.1.7 on 2021-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210306_0533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpresetlocation',
            options={'verbose_name': 'Preset Location', 'verbose_name_plural': 'Add Preset Loaction'},
        ),
        migrations.AlterField(
            model_name='userfavouritelist',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfavouritelist',
            name='latitude',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userfavouritelist',
            name='longtitude',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userfavouritelist',
            name='thumb_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userfavouritelist',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
